version: 0.1
project:
  name: overwatch-support
regions:
  us-west-2:
    stages:
      dev:
        enabled: true
        ecsPrometheusWriteEndpoint: ${PROMETHEUS_WRITE_ENDPOINT_OREGON}
        applicationPrometheusWriteEndpoint: ${PROMETHEUS_WRITE_ENDPOINT_OREGON}
      test:
        enabled: false
        ecsPrometheusWriteEndpoint: ${PROMETHEUS_WRITE_ENDPOINT_OREGON}
        applicationPrometheusWriteEndpoint: ${PROMETHEUS_WRITE_ENDPOINT_OREGON}
      stage:
        enabled: false
        ecsPrometheusWriteEndpoint: ${PROMETHEUS_WRITE_ENDPOINT_OREGON}
        applicationPrometheusWriteEndpoint: ${PROMETHEUS_WRITE_ENDPOINT_OREGON}
      prod:
        enabled: false
        ecsPrometheusWriteEndpoint: ${PROMETHEUS_WRITE_ENDPOINT_OREGON}
        applicationPrometheusWriteEndpoint: ${PROMETHEUS_WRITE_ENDPOINT_OREGON}

  # Add empty replication regions for non Oregon regions
  eu-west-1:
    stages:
      dev:
        enabled: false
        ecsPrometheusWriteEndpoint: ${PROMETHEUS_WRITE_ENDPOINT_DUB}
        applicationPrometheusWriteEndpoint: ${PROMETHEUS_WRITE_ENDPOINT_DUB}
